{
 "title": "service-user",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "percentile", "query": "0.5,0.95,0.99,max" }
  ]
 },
 "panels": [
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (exported_endpoint, method) (histogram_quantile($percentile,rate(response_time_bucket{status=\"200\"}[2m]) * 60))",
     "legendFormat": "{{exported_endpoint}}.{{method}}"
    }
   ]
  },
  {
   "title": "Response Time max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (exported_endpoint, method) (histogram_quantile(1,rate(response_time_bucket{status=\"200\"}[1m]) * 60))",
     "legendFormat": "{{exported_endpoint}}.{{method}}"
    }
   ]
  },
  {
   "title": "Response Time [NGINX Ingress]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (method, status)(\n  histogram_quantile($percentile,\n      rate(\n        nginx_ingress_controller_response_duration_seconds_bucket{\n          ingress =\"users\"\n        }[1m]\n      )\n  )\n)"
    }
   ]
  },
  {
   "title": "Response Time  max [NGINX Ingress]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (method, status)(\n  histogram_quantile(1,\n      rate(\n        nginx_ingress_controller_response_duration_seconds_bucket{\n          ingress =\"users\"\n        }[1m]\n      )\n  )\n)"
    }
   ]
  },
  {
   "title": "Error Rate [5XX] count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint, method) (rate(response_time_count{status=~\"5.*\"}[2m]) * 60)",
     "legendFormat": "{{exported_endpoint}}.{{method}}"
    }
   ]
  },
  {
   "title": "Error Rate [5XX] count [NGINX Ingress]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_response_duration_seconds_count{ingress =\"users\", status=~\"5.*\"}[2m]) * 60)"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint, method, status) (rate(response_time_count[2m]) * 60)",
     "legendFormat": "{{exported_endpoint}}.{{status}}"
    }
   ]
  },
  {
   "title": "RPM [NGINX Ingress]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_response_duration_seconds_count{ingress =\"users\"}[2m]) * 60)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{container=\"users\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=~\"users\"}",
     "legendFormat": "{{container}}.{{name}}.{{instance}}"
    }
   ]
  }
 ]
}