{{-  $host := printf "%s-prometheus" .Release.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  labels:
    {{- include "users.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://{{ template "grafana.prometheus.address" . }}:{{ index .Values "kube-prometheus" "prometheus" "service" "port" }}
      access: proxy
      isDefault: true