apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users.fullname" . }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: otus-hw2
  template:
    metadata:
      labels:
        app: otus-hw2
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: web-service
              containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "common.names.fullname" . }}
                  key: psql_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "common.names.fullname" . }}
                  key: psql_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ template "common.names.fullname" . }}
                  key: psql_db
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ template "common.names.fullname" . }}
                  key: psql_host
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
      volumes:
        - name: secrets
          secret:
            secretName: {{ template "common.names.fullname" . }}