apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "users.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - backend:
              service:
                name: {{ include "users.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            pathType: Prefix
            path: /service-user/(.*)