{{-  $pgHost := printf "%s-postgresql" .Release.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  psql_user: {{ include "postgresql.username" . | b64enc | quote }}
  psql_password: {{ include "postgresql.password" . | b64enc | quote }}
  psql_host: {{ $pgHost | b64enc | quote }}
  psql_db: {{ (include "postgresql.database" .) | b64enc | quote }}