apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "users.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
    monitoring: {{ .Values.ingress.monitoring | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "users.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            pathType: Prefix
            path: /service-user/(.*)