{{-  $pgHost := printf "%s-postgresql" .Release.Name -}}
{{-  $pgUri := printf "postgresql://%s:%s@%s/%s?sslmode=disable" (include "postgresql.username" .)  (include "postgresql.password" .) $pgHost (include "postgresql.database" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    {{- include "users.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  psql_user: {{ include "postgresql.username" . | b64enc | quote }}
  psql_password: {{ include "postgresql.password" . | b64enc | quote }}
  psql_host: {{ $pgHost | b64enc | quote }}
  psql_db: {{ (include "postgresql.database" .) | b64enc | quote }}
  psql_uri: {{ $pgUri | b64enc | quote }}