apiVersion: v1
kind: Service
metadata:
  name: {{ include "users.fullname" . }}
  labels:
    {{- include "users.labels" . | nindent 4 }}
    monitoring: {{ .Values.service.monitoring | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web-service
      protocol: TCP
      name: http
  selector:
    app: otus-hw2
