apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: required-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-url: http://auth.{{ .Release.Namespace }}.svc.cluster.local:80/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-user-id
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: user
                port:
                  number: {{ .Values.service.port }}
            pathType: Prefix
            path: /service-user/(.*)
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: no-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: auth
                port:
                  number: {{ .Values.service.port }}
            pathType: Prefix
            path: /(login|register)