apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    {{- include "users.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web-service
      protocol: TCP
      name: http
  selector:
    app: user
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    {{- include "users.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web-service
      protocol: TCP
      name: http
  selector:
    app: auth
